name: newtonheath
title: newtonheath
email: michael@virtualworthington.com
description: >- # this means to ignore newlines until "baseurl:"
  A catchall for recipes, things to remember, things to review
baseurl: /
url: https://newtonheath.github.io
twitter_username: newtonheath
github_username:  newtonheath
google_analytics: 'UA-136219422-1'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
